[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pgsql",
  "php82Extensions.pdo_pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.zip",
  "php82Extensions.tokenizer",
  "php82Extensions.ctype"
]

[phases.install]
cmds = [
  "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
  "curl -sS https://getcomposer.org/installer | php82 -- --install-dir=/usr/local/bin --filename=composer",
  "composer install --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"